/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai-insights/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ai Suggestions */
        get: operations["get_ai_suggestions_api_ai_insights__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify Email From Link */
        get: operations["verify_email_from_link_api_auth_verify_email_get"];
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        /**
         * Create Course
         * @description Create a custom course for a user.
         */
        post: operations["create_course_api_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Courses */
        get: operations["search_courses_api_courses_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_courses__course_id__get"];
        /**
         * Update Course
         * @description Update a custom course. Only the owner can edit; master courses are protected.
         */
        put: operations["update_course_api_courses__course_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{course_id}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Course
         * @description Clone a master course as a user-owned custom course.
         */
        post: operations["clone_course_api_courses__course_id__clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rounds For User */
        get: operations["get_rounds_for_user_api_rounds_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round */
        get: operations["get_round_api_rounds__round_id__get"];
        /**
         * Update Round
         * @description Edit an existing round's scores and/or metadata.
         */
        put: operations["update_round_api_rounds__round_id__put"];
        post?: never;
        /** Delete Round */
        delete: operations["delete_round_api_rounds__round_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rounds/{round_id}/link-course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link Course To Round
         * @description Link an unlinked round to an existing course.
         *
         *     Backfills par_played/handicap_played on hole_scores from the course,
         *     and fills course holes from any par_played already on the round.
         */
        post: operations["link_course_to_round_api_rounds__round_id__link_course_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Scan
         * @description Upload a scorecard image, run OCR extraction, return results for review.
         */
        post: operations["extract_scan_api_scan_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prefetch Ocr
         * @description Run OCR on an uploaded image and return the raw markdown text.
         *
         *     Called immediately on file selection so the slow OCR step is already
         *     complete by the time the user clicks Extract.
         */
        post: operations["prefetch_ocr_api_scan_ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Round
         * @description Save a reviewed/edited round to the database.
         */
        post: operations["save_round_api_scan_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/analytics/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_stats_analytics__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/compare/{user_id}/{round_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Round Comparison */
        get: operations["get_round_comparison_api_stats_compare__user_id___round_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/course-analytics/{user_id}/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Analytics */
        get: operations["get_course_analytics_api_stats_course_analytics__user_id___course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/dashboard/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_stats_dashboard__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/milestones/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Milestones
         * @description Return a flat, sorted list of lifetime milestone events for the user.
         */
        get: operations["get_milestones_api_stats_milestones__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/{user_id}/goal-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal Report */
        get: operations["get_goal_report_api_stats__user_id__goal_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/{user_id}/played-courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Played Courses
         * @description Return distinct courses the user has rounds linked to.
         */
        get: operations["get_played_courses_api_stats__user_id__played_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/by-email/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User By Email */
        get: operations["get_user_by_email_api_users_by_email__email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Friendships
         * @description List friendships for the current user.
         */
        get: operations["list_friendships_api_users_me_friends_get"];
        put?: never;
        /**
         * Send Friend Request
         * @description Send (or re-open) a friend request to another user.
         */
        post: operations["send_friend_request_api_users_me_friends_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/friends/{friendship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Friendship Status
         * @description Accept/decline/block a friendship request.
         */
        patch: operations["update_friendship_status_api_users_me_friends__friendship_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/handicap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Handicap
         * @description Return the user's current WHS Handicap Index.
         */
        get: operations["get_user_handicap_api_users__user_id__handicap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/tees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Tees
         * @description List a user's custom tee configurations.
         */
        get: operations["get_user_tees_api_users__user_id__tees_get"];
        put?: never;
        /**
         * Create User Tee
         * @description Create a user tee configuration.
         */
        post: operations["create_user_tee_api_users__user_id__tees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/tees/{tee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update User Tee
         * @description Update a user tee configuration.
         */
        put: operations["update_user_tee_api_users__user_id__tees__tee_id__put"];
        post?: never;
        /**
         * Delete User Tee
         * @description Delete a user tee configuration.
         */
        delete: operations["delete_user_tee_api_users__user_id__tees__tee_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIComparisonItem */
        AIComparisonItem: {
            /** Benchmark Value */
            benchmark_value: number;
            /** Category */
            category: string;
            /** Has Data */
            has_data: boolean;
            /** Lower Is Better */
            lower_is_better: boolean;
            /** Metric */
            metric: string;
            /** Player Value */
            player_value: number | null;
            /** Unit */
            unit: string;
        };
        /** AIInsightItem */
        AIInsightItem: {
            /** Benchmark */
            benchmark: number | null;
            /** Category */
            category: string;
            /** Category Group */
            category_group: string;
            /** Description */
            description: string;
            /** Drill Tips */
            drill_tips: string[];
            /** Key Metric */
            key_metric: number | null;
            /** Metric Label */
            metric_label: string;
            /** Priority Score */
            priority_score: number;
            /** Title */
            title: string;
            /** Trend Direction */
            trend_direction: string;
            /** What If */
            what_if: string | null;
        };
        /** AIStrengthItem */
        AIStrengthItem: {
            /** Benchmark Value */
            benchmark_value: number;
            /** Category */
            category: string;
            /** Margin Description */
            margin_description: string;
            /** Metric Label */
            metric_label: string;
            /** Player Value */
            player_value: number;
            /** Title */
            title: string;
        };
        /** AISuggestionsResponse */
        AISuggestionsResponse: {
            /** Comparisons */
            comparisons: components["schemas"]["AIComparisonItem"][];
            /** Generated At */
            generated_at: string;
            /** Handicap Index */
            handicap_index: number | null;
            /** Handicap Range Label */
            handicap_range_label: string;
            /** Insights */
            insights: components["schemas"]["AIInsightItem"][];
            /** Rounds Analyzed */
            rounds_analyzed: number;
            /** Strengths */
            strengths: components["schemas"]["AIStrengthItem"][];
            /** User Id */
            user_id: string;
        };
        /** AuthUserResponse */
        AuthUserResponse: {
            /** Access Token */
            access_token?: string | null;
            /** Email */
            email: string;
            /**
             * Email Verified
             * @default true
             */
            email_verified: boolean;
            /** Name */
            name: string;
            /** User Id */
            user_id: string;
        };
        /** Body_extract_scan_api_scan_extract_post */
        Body_extract_scan_api_scan_extract_post: {
            /** Course Id */
            course_id?: string | null;
            /** File */
            file: string;
            /** Ocr Text */
            ocr_text?: string | null;
            /** User Context */
            user_context?: string | null;
        };
        /** Body_prefetch_ocr_api_scan_ocr_post */
        Body_prefetch_ocr_api_scan_ocr_post: {
            /** File */
            file: string;
        };
        /**
         * CourseAnalyticsResponse
         * @description The player's figures at one course. Every figure is worked out here, not on the client.
         */
        CourseAnalyticsResponse: {
            /** Average Putts By Hole */
            average_putts_by_hole: components["schemas"]["CourseHolePuttsRow"][];
            /** Average Score Relative To Par By Hole */
            average_score_relative_to_par_by_hole: components["schemas"]["CourseHoleToParRow"][];
            /** Average Score When Gir Vs Missed */
            average_score_when_gir_vs_missed: components["schemas"]["CourseGirImpactRow"][];
            /** Best Score */
            best_score: number | null;
            /** Course Difficulty Profile By Hole */
            course_difficulty_profile_by_hole: components["schemas"]["CourseHoleDifficultyRow"][];
            /** Course Id */
            course_id: string;
            /** Gir Percentage By Hole */
            gir_percentage_by_hole: components["schemas"]["CourseHoleGirRow"][];
            /** Rounds */
            rounds: components["schemas"]["RoundSummaryResponse"][];
            /** Rounds Played */
            rounds_played: number;
            /** Score Trend On Course */
            score_trend_on_course: components["schemas"]["CourseScoreTrendRow"][];
            /** Score Type Distribution By Hole */
            score_type_distribution_by_hole: components["schemas"]["CourseHoleScoreTypeRow"][];
            /** Score Variance By Hole */
            score_variance_by_hole: components["schemas"]["CourseHoleVarianceRow"][];
            /** Scoring Average */
            scoring_average: number | null;
            /** Worst Score */
            worst_score: number | null;
        };
        /** CourseGirImpactRow */
        CourseGirImpactRow: {
            /** Average Score */
            average_score: number | null;
            /** Average To Par */
            average_to_par: number | null;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "GIR" | "No GIR";
            /** Holes Counted */
            holes_counted: number;
        };
        /** CourseHoleDifficultyRow */
        CourseHoleDifficultyRow: {
            /** Average Score */
            average_score: number;
            /** Average To Par */
            average_to_par: number;
            /** Difficulty Rank */
            difficulty_rank: number;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Sample Size */
            sample_size: number;
        };
        /** CourseHoleGirRow */
        CourseHoleGirRow: {
            /** Gir Hits */
            gir_hits: number;
            /** Gir Percentage */
            gir_percentage: number;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Sample Size */
            sample_size: number;
        };
        /** CourseHoleInput */
        CourseHoleInput: {
            /** Handicap */
            handicap?: number | null;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par?: number | null;
        };
        /** CourseHolePuttsRow */
        CourseHolePuttsRow: {
            /** Average Putts */
            average_putts: number;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Sample Size */
            sample_size: number;
        };
        /**
         * CourseHoleScoreTypeRow
         * @description Percent of rounds that landed in each score type on the hole. `par` is the par percentage.
         */
        CourseHoleScoreTypeRow: {
            /** Birdie */
            birdie: number;
            /** Bogey */
            bogey: number;
            /** Double Bogey */
            double_bogey: number;
            /** Eagle */
            eagle: number;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Quad Bogey */
            quad_bogey: number;
            /** Sample Size */
            sample_size: number;
            /** Triple Bogey */
            triple_bogey: number;
        };
        /** CourseHoleToParRow */
        CourseHoleToParRow: {
            /** Average Score */
            average_score: number;
            /** Average To Par */
            average_to_par: number;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Sample Size */
            sample_size: number;
        };
        /** CourseHoleVarianceRow */
        CourseHoleVarianceRow: {
            /** Average Score */
            average_score: number | null;
            /** Hole Number */
            hole_number: number;
            /** Par */
            par: number;
            /** Sample Size */
            sample_size: number;
            /** Score Std Dev */
            score_std_dev: number | null;
            /** Score Variance */
            score_variance: number | null;
            /** Variance Rank */
            variance_rank: number;
        };
        /**
         * CourseResponse
         * @description A full course, with the figures the Course model works out.
         */
        CourseResponse: {
            /** Back Nine Par */
            back_nine_par: number | null;
            /** External Course Id */
            external_course_id: string | null;
            /** Front Nine Par */
            front_nine_par: number | null;
            /** Holes */
            holes: components["schemas"]["Hole"][];
            /** Id */
            id: string | null;
            /** Location */
            location: string | null;
            /** Name */
            name: string | null;
            /** Par */
            par: number | null;
            /** Tees */
            tees: components["schemas"]["TeeResponse"][];
            /** User Id */
            user_id: string | null;
        };
        /**
         * CourseScoreTrendRow
         * @description One round at the course, oldest first.
         */
        CourseScoreTrendRow: {
            /** Date */
            date: string | null;
            /** Round Id */
            round_id: string | null;
            /** Round Index */
            round_index: number;
            /** To Par */
            to_par: number | null;
            /** Total Score */
            total_score: number | null;
        };
        /**
         * CourseSummaryResponse
         * @description Course for card/list views.
         */
        CourseSummaryResponse: {
            /** External Course Id */
            external_course_id: string | null;
            /** Id */
            id: string;
            /** Location */
            location: string | null;
            /** Name */
            name: string | null;
            /** Par */
            par: number | null;
            /**
             * Source
             * @default local
             */
            source: string;
            /**
             * Tee Count
             * @default 0
             */
            tee_count: number;
            /**
             * Total Holes
             * @default 0
             */
            total_holes: number;
        };
        /** CreateCourseRequest */
        CreateCourseRequest: {
            /** External Course Id */
            external_course_id?: string | null;
            /** Holes */
            holes?: components["schemas"]["HoleInput"][];
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Tees */
            tees?: components["schemas"]["api__routers__courses__TeeInput"][];
        };
        /** CreateUserTeeRequest */
        CreateUserTeeRequest: {
            /** Course Id */
            course_id?: string | null;
            /** Course Rating */
            course_rating?: number | null;
            /** Hole Yardages */
            hole_yardages?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name: string;
            /** Slope Rating */
            slope_rating?: number | null;
        };
        /**
         * DashboardResponse
         * @description Aggregated stats for the dashboard page. Every figure is worked out here, not on the client.
         */
        DashboardResponse: {
            /** Average Gir */
            average_gir: number | null;
            /** Average Putts */
            average_putts: number | null;
            /** Best Round */
            best_round: number | null;
            /** Best Round Course */
            best_round_course: string | null;
            /** Best Round Id */
            best_round_id: string | null;
            handicap_change: components["schemas"]["HandicapChange"];
            /** Handicap Index */
            handicap_index: number | null;
            /** Milestones */
            milestones: components["schemas"]["Milestone"][];
            recent_form: components["schemas"]["RecentForm"];
            /** Recent Rounds */
            recent_rounds: components["schemas"]["RoundSummaryResponse"][];
            recent_score_mix: components["schemas"]["ScoreMix"];
            score_mix: components["schemas"]["ScoreMix"];
            /**
             * Score Mix Holes
             * @default 0
             */
            score_mix_holes: number;
            /** Scoring Average */
            scoring_average: number | null;
            /** Scoring Average L20 */
            scoring_average_l20: number | null;
            /** Scoring Average L5 */
            scoring_average_l5: number | null;
            /** Total Rounds */
            total_rounds: number;
            whs: components["schemas"]["WhsBreakdown"];
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /** FriendshipResponse */
        FriendshipResponse: {
            /** Addressee Email */
            addressee_email?: string | null;
            /** Addressee Id */
            addressee_id: string;
            /** Addressee Name */
            addressee_name?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Requester Email */
            requester_email?: string | null;
            /** Requester Id */
            requester_id: string;
            /** Requester Name */
            requester_name?: string | null;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** FriendshipStatusRequest */
        FriendshipStatusRequest: {
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandicapChange */
        HandicapChange: {
            /** Delta */
            delta: number | null;
            /** Direction */
            direction: ("up" | "down" | "flat") | null;
        };
        /**
         * Hole
         * @description Represents a single hole on a golf course.
         */
        Hole: {
            /** Handicap */
            handicap: number | null;
            /** Number */
            number: number | null;
            /** Par */
            par: number | null;
        };
        /** HoleInput */
        HoleInput: {
            /** Handicap */
            handicap?: number | null;
            /** Number */
            number: number;
            /** Par */
            par?: number | null;
        };
        /** HoleScoreInput */
        HoleScoreInput: {
            /** Fairway Hit */
            fairway_hit?: boolean | null;
            /** Green In Regulation */
            green_in_regulation?: boolean | null;
            /** Handicap Played */
            handicap_played?: number | null;
            /** Hole Number */
            hole_number: number;
            /** Net Score */
            net_score?: number | null;
            /** Par Played */
            par_played?: number | null;
            /** Putts */
            putts?: number | null;
            /** Shots To Green */
            shots_to_green?: number | null;
            /** Strokes */
            strokes?: number | null;
        };
        /**
         * HoleScoreResponse
         * @description One hole as played, with its par resolved and how it scored.
         */
        HoleScoreResponse: {
            /** Fairway Hit */
            fairway_hit: boolean | null;
            /** Green In Regulation */
            green_in_regulation: boolean | null;
            /** Handicap Played */
            handicap_played: number | null;
            /** Hole Number */
            hole_number: number;
            /** Kind */
            kind: ("eagle" | "birdie" | "par" | "bogey" | "double" | "triple" | "quad") | null;
            /** Net Score */
            net_score: number | null;
            /** Par */
            par: number | null;
            /** Par Played */
            par_played: number | null;
            /** Putts */
            putts: number | null;
            /** Shots To Green */
            shots_to_green: number | null;
            /** Strokes */
            strokes: number | null;
            /** To Par */
            to_par: number | null;
        };
        /** HoleScoreUpdate */
        HoleScoreUpdate: {
            /** Fairway Hit */
            fairway_hit?: boolean | null;
            /** Green In Regulation */
            green_in_regulation?: boolean | null;
            /** Handicap Played */
            handicap_played?: number | null;
            /** Hole Number */
            hole_number: number;
            /** Net Score */
            net_score?: number | null;
            /** Par Played */
            par_played?: number | null;
            /** Putts */
            putts?: number | null;
            /** Shots To Green */
            shots_to_green?: number | null;
            /** Strokes */
            strokes?: number | null;
        };
        /** LinkCourseRequest */
        LinkCourseRequest: {
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * Milestone
         * @description A lifetime best. `value` is the score, the putt threshold, or the streak length.
         */
        Milestone: {
            /** Course */
            course: string;
            /** Date */
            date: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "under_par" | "score_break" | "putt_break" | "par_streak";
            /** Round Id */
            round_id: string | null;
            /** Value */
            value: number;
        };
        /**
         * RecentForm
         * @description Rates over the last five rounds, pooled by chances. Null when there is nothing to measure.
         */
        RecentForm: {
            /** Gir Pct */
            gir_pct: number | null;
            /** Putts Per 18 */
            putts_per_18: number | null;
            /** Scrambling Pct */
            scrambling_pct: number | null;
            /** Up And Down Pct */
            up_and_down_pct: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Handicap */
            handicap?: number | null;
            /** Home Course Id */
            home_course_id?: string | null;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Message */
            message: string;
            /**
             * Requires Email Verification
             * @default true
             */
            requires_email_verification: boolean;
        };
        /** ResendVerificationRequest */
        ResendVerificationRequest: {
            /** Email */
            email: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /**
         * RoundResponse
         * @description A full round: the stored round, its figures, and its hole scores.
         */
        RoundResponse: {
            /** Back Nine */
            back_nine: number | null;
            course: components["schemas"]["CourseResponse"] | null;
            /** Course Name Played */
            course_name_played: string | null;
            /** Date */
            date: string | null;
            /** Fairways Hit */
            fairways_hit: number | null;
            /** Front Nine */
            front_nine: number | null;
            /** Hole Scores */
            hole_scores: components["schemas"]["HoleScoreResponse"][];
            /** Id */
            id: string | null;
            /** Notes */
            notes: string | null;
            /** Par */
            par: number | null;
            score_counts: components["schemas"]["ScoreCounts"];
            /** Tee Box */
            tee_box: string | null;
            /** To Par */
            to_par: number | null;
            /** Total Gir */
            total_gir: number | null;
            /** Total Putts */
            total_putts: number | null;
            /** Total Score */
            total_score: number | null;
            user_tee: components["schemas"]["UserTee"] | null;
            /** Weather Conditions */
            weather_conditions: string | null;
        };
        /**
         * RoundSummaryResponse
         * @description A round for list views: where and when, its figures, and its hole scores.
         */
        RoundSummaryResponse: {
            /** Back Nine */
            back_nine: number | null;
            /** Course Id */
            course_id: string | null;
            /** Course Location */
            course_location: string | null;
            /** Course Name */
            course_name: string | null;
            /** Course Par */
            course_par: number | null;
            /** Date */
            date: string | null;
            /** Fairways Hit */
            fairways_hit: number | null;
            /** Front Nine */
            front_nine: number | null;
            /** Hole Scores */
            hole_scores: components["schemas"]["HoleScoreResponse"][];
            /** Id */
            id: string;
            /** Notes */
            notes: string | null;
            /** Par */
            par: number | null;
            score_counts: components["schemas"]["ScoreCounts"];
            /** Tee Box */
            tee_box: string | null;
            /** To Par */
            to_par: number | null;
            /** Total Gir */
            total_gir: number | null;
            /** Total Putts */
            total_putts: number | null;
            /** Total Score */
            total_score: number | null;
        };
        /**
         * SaveRoundRequest
         * @description Request to save a reviewed/edited round.
         */
        SaveRoundRequest: {
            /** All Tees */
            all_tees?: components["schemas"]["api__request_models__TeeInput"][] | null;
            /** Course Holes */
            course_holes?: components["schemas"]["CourseHoleInput"][] | null;
            /** Course Id */
            course_id?: string | null;
            /** Course Location */
            course_location?: string | null;
            /** Course Name */
            course_name?: string | null;
            /** Date */
            date?: string | null;
            /** External Course Id */
            external_course_id?: string | null;
            /** Hole Scores */
            hole_scores: components["schemas"]["HoleScoreInput"][];
            /** Notes */
            notes?: string | null;
            /** Tee Box */
            tee_box?: string | null;
            /** Tee Course Rating */
            tee_course_rating?: number | null;
            /** Tee Slope Rating */
            tee_slope_rating?: number | null;
            /** Tee Yardages */
            tee_yardages?: {
                [key: string]: number | null;
            } | null;
            /**
             * User Id
             * @default
             */
            user_id: string;
        };
        /**
         * ScoreCounts
         * @description How many holes landed in each score bucket.
         */
        ScoreCounts: {
            /**
             * Birdie
             * @default 0
             */
            birdie: number;
            /**
             * Bogey
             * @default 0
             */
            bogey: number;
            /**
             * Double
             * @default 0
             */
            double: number;
            /**
             * Eagle
             * @default 0
             */
            eagle: number;
            /**
             * Par
             * @default 0
             */
            par: number;
            /**
             * Quad
             * @default 0
             */
            quad: number;
            /**
             * Triple
             * @default 0
             */
            triple: number;
        };
        /**
         * ScoreMix
         * @description Percent of classified holes in each score bucket.
         */
        ScoreMix: {
            /**
             * Birdie
             * @default 0
             */
            birdie: number;
            /**
             * Bogey
             * @default 0
             */
            bogey: number;
            /**
             * Double
             * @default 0
             */
            double: number;
            /**
             * Eagle
             * @default 0
             */
            eagle: number;
            /**
             * Par
             * @default 0
             */
            par: number;
            /**
             * Quad
             * @default 0
             */
            quad: number;
            /**
             * Triple
             * @default 0
             */
            triple: number;
        };
        /** SendFriendRequest */
        SendFriendRequest: {
            /** Addressee Friend Code */
            addressee_friend_code?: string | null;
            /** Addressee User Id */
            addressee_user_id?: string | null;
        };
        /**
         * TeeResponse
         * @description A tee with its yardage figures worked out.
         */
        TeeResponse: {
            /** Back Nine Yardage */
            back_nine_yardage: number | null;
            /** Color */
            color: string | null;
            /** Course Rating */
            course_rating: number | null;
            /** Front Nine Yardage */
            front_nine_yardage: number | null;
            /** Hole Yardages */
            hole_yardages: {
                [key: string]: number;
            };
            /** Slope Rating */
            slope_rating: number | null;
            /** Total Yardage */
            total_yardage: number | null;
        };
        /** UpdateCourseRequest */
        UpdateCourseRequest: {
            /** External Course Id */
            external_course_id?: string | null;
            /** Location */
            location?: string | null;
            /** Name */
            name?: string | null;
            /** Par */
            par?: number | null;
        };
        /** UpdateRoundRequest */
        UpdateRoundRequest: {
            /** Course Name Played */
            course_name_played?: string | null;
            /** Hole Scores */
            hole_scores?: components["schemas"]["HoleScoreUpdate"][] | null;
            /** Notes */
            notes?: string | null;
            /** Tee Box */
            tee_box?: string | null;
            /** Weather Conditions */
            weather_conditions?: string | null;
        };
        /** UpdateUserRequest */
        UpdateUserRequest: {
            /** Handicap */
            handicap?: number | null;
            /** Home Course Id */
            home_course_id?: string | null;
            /** Scoring Goal */
            scoring_goal?: number | null;
        };
        /** UpdateUserTeeRequest */
        UpdateUserTeeRequest: {
            /** Course Rating */
            course_rating?: number | null;
            /** Hole Yardages */
            hole_yardages?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name?: string | null;
            /** Slope Rating */
            slope_rating?: number | null;
        };
        /**
         * UserTee
         * @description A user-owned tee configuration, optionally linked to a master course.
         */
        UserTee: {
            /** Course Id */
            course_id: string | null;
            /** Course Rating */
            course_rating: number | null;
            /** Created At */
            created_at: string | null;
            /** Hole Yardages */
            hole_yardages: {
                [key: string]: number;
            };
            /** Id */
            id: string | null;
            /** Name */
            name: string;
            /** Slope Rating */
            slope_rating: number | null;
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
        /**
         * WhsBreakdown
         * @description The rounds in the handicap window, newest first, and which differentials count.
         */
        WhsBreakdown: {
            /**
             * Adjustment
             * @default 0
             */
            adjustment: number;
            /**
             * Count Used
             * @default 0
             */
            count_used: number;
            /** Diff Avg */
            diff_avg: number | null;
            /**
             * Has Rated Rounds
             * @default false
             */
            has_rated_rounds: boolean;
            /** Rows */
            rows: components["schemas"]["WhsRound"][];
            /**
             * Show Calculation
             * @default false
             */
            show_calculation: boolean;
            /**
             * Window Size
             * @default 0
             */
            window_size: number;
        };
        /** WhsRound */
        WhsRound: {
            /** Course Name */
            course_name: string | null;
            /** Course Rating */
            course_rating: number | null;
            /** Differential */
            differential: number | null;
            /** Round Index */
            round_index: number;
            /** Score */
            score: number | null;
            /** Slope Rating */
            slope_rating: number | null;
            /**
             * Used
             * @default false
             */
            used: boolean;
        };
        /** TeeInput */
        api__request_models__TeeInput: {
            /** Color */
            color: string;
            /** Course Rating */
            course_rating?: number | null;
            /** Hole Yardages */
            hole_yardages?: {
                [key: string]: number | null;
            };
            /** Slope Rating */
            slope_rating?: number | null;
        };
        /** TeeInput */
        api__routers__courses__TeeInput: {
            /** Color */
            color: string;
            /** Course Rating */
            course_rating?: number | null;
            /** Hole Yardages */
            hole_yardages?: {
                [key: string]: unknown;
            };
            /** Slope Rating */
            slope_rating?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_ai_suggestions_api_ai_insights__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
                target_handicap?: number | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_from_link_api_auth_verify_email_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_course_api_courses_post: {
        parameters: {
            query?: {
                /** @description Owner user ID for the custom course */
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_courses_api_courses_search_get: {
        parameters: {
            query: {
                q: string;
                user_id?: string | null;
                /** @description When true, include GolfCourseAPI fallback results after local search. */
                include_external?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_api_courses__course_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_course_api_courses__course_id__clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rounds_for_user_api_rounds_user__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_api_rounds__round_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_round_api_rounds__round_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_round_api_rounds__round_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_course_to_round_api_rounds__round_id__link_course_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                round_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkCourseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_scan_api_scan_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_scan_api_scan_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prefetch_ocr_api_scan_ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_prefetch_ocr_api_scan_ocr_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_round_api_scan_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRoundRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_stats_analytics__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
                course_id?: string | null;
                timeframe?: ("ytd" | "1y") | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_round_comparison_api_stats_compare__user_id___round_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                round_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_analytics_api_stats_course_analytics__user_id___course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_stats_dashboard__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_milestones_api_stats_milestones__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_report_api_stats__user_id__goal_report_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_played_courses_api_stats__user_id__played_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_by_email_api_users_by_email__email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_friendships_api_users_me_friends_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_friend_request_api_users_me_friends_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendFriendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_friendship_status_api_users_me_friends__friendship_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                friendship_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FriendshipStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_handicap_api_users__user_id__handicap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_tees_api_users__user_id__tees_get: {
        parameters: {
            query?: {
                course_id?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTee"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_tee_api_users__user_id__tees_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserTeeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTee"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_tee_api_users__user_id__tees__tee_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                tee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserTeeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTee"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_tee_api_users__user_id__tees__tee_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                tee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
